services:
  app_proxy:
    environment:
      APP_HOST: drumfeet-pricewatch_web_1
      APP_PORT: 3000
  web:
    image: ghcr.io/drumfeet/pricewatch:0.1.12@sha256:d608bdfdcda33ad59f9f3c1dec414e49242585f1a126114ddaf71bd02a29098c
    security_opt:
      - apparmor=drumfeet-pricewatch
      - seccomp=${APP_DATA_DIR}/seccomp.json
    init: true
    restart: on-failure
    stop_grace_period: 30s
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      DATA_DIR: /data
      ALLOW_PRIVATE_HOSTS: "true"
      ALLOWED_HOSTS: localhost,127.0.0.1,${DEVICE_DOMAIN_NAME},drumfeet-pricewatch_web_1
    volumes:
      - ${APP_DATA_DIR}/data:/data
    shm_size: 256mb
