services:
  app_proxy:
    environment:
      APP_HOST: drumfeet-pricewatch_web_1
      APP_PORT: 3000
  web:
    image: ghcr.io/drumfeet/pricewatch:0.1.8@sha256:cfb2f21f06a689acfab9015ece733a6e82fa190ca20f59507ac64dd5526b81a4
    security_opt:
      - apparmor=drumfeet-pricewatch
      - seccomp=${APP_DATA_DIR}/seccomp.json
    init: true
    restart: on-failure
    stop_grace_period: 30s
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      DATA_DIR: /data
      ALLOW_PRIVATE_HOSTS: "true"
      ALLOWED_HOSTS: localhost,127.0.0.1,${DEVICE_DOMAIN_NAME},drumfeet-pricewatch_web_1
    volumes:
      - ${APP_DATA_DIR}/data:/data
    shm_size: 256mb
