version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: drumfeet-visual-status-checker_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/drumfeet/visual-status-checker:0.1.13@sha256:6795436dfeebe8b8c45fc5308b0e11e702d0d968eef17707fa1d069e30c87179
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      MINIMUM_CHECK_INTERVAL_MS: "900000"
