version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: drumfeet-visual-status-checker_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/drumfeet/visual-status-checker:0.1.18@sha256:2e6f1426a1857b5797a2e17306da4c7c6deb796d3daef12c0a29c17610c7c86d
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      MINIMUM_CHECK_INTERVAL_MS: "900000"
