version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: drumfeet-visual-status-checker_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/drumfeet/visual-status-checker:0.1.14@sha256:85b6684f03212c54235eaaf19a13c47814e78bd9bdf593c2d7485a22b58b6c14
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      MINIMUM_CHECK_INTERVAL_MS: "900000"
